---
- hosts: consul_server
  remote_user: vagrant
  become: true
  roles:
    - install_consul_server

- hosts: db
  remote_user: vagrant
  become: true
  roles:
    - install_consul_client
    - install_db

- hosts: api
  remote_user: vagrant
  become: true
  roles:
    - install_consul_client
    - install_hotels_service
