version: '3.8'

services:
  database:
    image: asskkord/asskkord-images:database

  booking-service:
    image: asskkord/asskkord-images:booking-service

  gateway-service:
    image: asskkord/asskkord-images:gateway-service
    ports:
      - "8087:8087"

  hotel-service:
    image: asskkord/asskkord-images:hotel-service

  loyalty-service:
    image: asskkord/asskkord-images:loyalty-service

  payment-service:
    image: asskkord/asskkord-images:payment-service

  report-service:
    image: asskkord/asskkord-images:report-service

  session-service:
    image: asskkord/asskkord-images:session-service
    ports:
      - "8081:8081"

  rabbit:
    image: asskkord/asskkord-images:rabbitmq