Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    vm_memory = 2048
    vm_cpu = 1
  
    manager_ip = "192.168.100.100"
    config.vm.define "manager" do |manager|
      manager.vm.hostname = "manager"
      manager.vm.network "private_network", ip: manager_ip
      manager.vm.provider "virtualbox" do |vb|
        vb.name = "manager02"
        vb.memory = vm_memory
        vb.cpus = vm_cpu
      end
    end
  
    consul_server_ip = "192.168.100.101"
    config.vm.define "consul_server" do |consul_server|
      consul_server.vm.hostname = "consulserver"
      consul_server.vm.network "private_network", ip: consul_server_ip
      consul_server.vm.network "forwarded_port", guest: 8500, host: 8500
      consul_server.vm.provider "virtualbox" do |vb|
        vb.name = "consul_server"
        vb.memory = vm_memory
        vb.cpus = vm_cpu
      end
    end
  
    api_ip = "192.168.100.102"
    config.vm.define "api" do |api|
      api.vm.hostname = "api"
      api.vm.network "private_network", ip: api_ip
      api.vm.network "forwarded_port", guest: 8082, host: 8082
      api.vm.provider "virtualbox" do |vb|
        vb.name = "api"
        vb.memory = vm_memory
        vb.cpus = vm_cpu
      end
    end

    db_ip = "192.168.100.103"
    config.vm.define "db" do |db|
      db.vm.hostname = "db"
      db.vm.network "private_network", ip: db_ip
      db.vm.provider "virtualbox" do |vb|
        vb.name = "db"
        vb.memory = vm_memory
        vb.cpus = vm_cpu
      end
    end
  end